#
# Stack for local development.
# Create a docker-compose.local.yml with your directories similar to:
#
#    services:
#      media-hare:
#        volumes:
#          - /path/to/host/data:/data
#
# Run with:
#     docker compose -p mh -f docker-compose.yml -f docker-compose.local.yml up --build -d
#
# export LANGUAGE_TOOL_HOST=localhost LANGUAGE_TOOL_PORT=8100 KALDI_EN_HOST=localhost KALDI_EN_PORT=2700
#

services:

  langtool:
    image: ghcr.io/double16/libreoffice-langtool:6.6
    platform: "linux/amd64"
    restart: unless-stopped
    ports:
      - "8100:8100/tcp"

