#
# Stack for local development.
# Create a docker-compose.local.yml with your directories similar to:
#
#    services:
#      media-hare:
#        volumes:
#          - /path/to/host/data:/data
#
# Run with:
#     docker compose -p mh -f docker-compose.yml -f docker-compose.local.yml up --build -d
#

services:

  langtool:
    image: ghcr.io/double16/libreoffice-langtool:6.5
    restart: unless-stopped
    ports:
      - "8100:8100/tcp"

  media-hare:
    build: .
    restart: unless-stopped
    volumes:
      - ${PWD}:/src
    environment:
      - "TZ=America/Chicago"
      - "LANGUAGE_TOOL_HOST=langtool"
      - "LANGUAGE_TOOL_PORT=8100"
      - "CRON_DISABLE=true"
