FROM ubuntu:22.04 as comskipbuild

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp
RUN apt-get -q update &&\
    apt-get install -y autoconf libtool git build-essential libargtable2-dev libavformat-dev libsdl1.2-dev libswscale-dev
RUN git clone https://github.com/erikkaashoek/Comskip --branch master --single-branch
RUN cd Comskip &&\
    git reset 8b5d7c98778018a97c46d598f0ce5fea27fa4a3b --hard
RUN cd Comskip &&\
    ./autogen.sh &&\
    ./configure &&\
    make &&\
    make install

FROM ubuntu:22.04

ARG SYSTEMCTL_VER=1.5.4505
ENV DEBIAN_FRONTEND=noninteractive

COPY requirements.txt /tmp/

# mono-* deps line must match Subtitle-Edit version
# vosk models: https://alphacephei.com/vosk/models
RUN apt-get -q update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:savoury1/ffmpeg4 -y && \
    add-apt-repository ppa:savoury1/ffmpeg5 -y && \
    apt-get install -qy zsh ffmpeg x264 x265 imagemagick vainfo curl python3 python3-pip python3-dev cron anacron sshfs vim-tiny mkvtoolnix unzip logrotate jq ccextractor \
    mono-runtime libmono-system-windows-forms4.0-cil libmono-system-net-http-webrequest4.0-cil mono-devel libhunspell-dev tesseract-ocr-eng xserver-xorg-video-dummy libgtk2.0-0 \
    libargtable2-0 libavformat58 libsdl1.2-compat &&\
    pip -q --no-input install -r /tmp/requirements.txt && \
    apt-get remove -y python3-pip software-properties-common &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* &&\
    find /etc/cron.*/* -type f -not -name "*logrotate*" -not -name "*anacron*" -delete &&\
    mkdir /root/.cache/vosk &&\
    curl -o /tmp/vosk-model-en-us-0.22-lgraph.zip -L --silent --fail https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-lgraph.zip &&\
    unzip -d /root/.cache/vosk /tmp/vosk-model-en-us-0.22-lgraph.zip &&\
    curl -o /tmp/vosk-model-small-es-0.22.zip -L --silent --fail https://alphacephei.com/vosk/models/vosk-model-small-es-0.22.zip &&\
    unzip -d /root/.cache/vosk /tmp/vosk-model-small-es-0.22.zip &&\
    rm -rf /tmp/*

# It appears Ubuntu does not include tesseract models for all OCR engines
# All of the 4.1.0 training data is available at https://github.com/tesseract-ocr/tessdata/archive/refs/tags/4.1.0.tar.gz
# We'll limit to English for now because of the size
# This is version 4.1.0, but it doesn't make things better
# ADD https://github.com/tesseract-ocr/tessdata/raw/4767ea922bcc460e70b87b1d303ebdfed0897da8/eng.traineddata /usr/share/tesseract-ocr/4.00/tessdata/

RUN curl -o /tmp/se.zip -L "https://github.com/SubtitleEdit/subtitleedit/releases/download/3.6.8/SE368.zip" &&\
    unzip -d /usr/share/subtitle-edit /tmp/se.zip &&\
    rm /tmp/se.zip &&\
    curl -L -o /usr/bin/systemctl https://github.com/gdraheim/docker-systemctl-replacement/raw/v${SYSTEMCTL_VER}/files/docker/systemctl3.py &&\
    chmod +x /usr/bin/systemctl &&\
    useradd -g 100 -u 99 plex &&\
    mv /usr/bin/tesseract /usr/bin/tesseract.orig

# Settings.xml is generated by running SubtitleEdit.exe and exiting. If re-generating, compare settings. Ensure that the subtitle PNGs are not transparent.
COPY SubtitleEdit-Settings.xml /usr/share/subtitle-edit/Settings.xml
ADD subtitle-edit /usr/local/bin/
COPY --from=comskipbuild /usr/local/bin/comskip /usr/local/bin
ADD dvrprocess /usr/local/share/dvrprocess/
RUN find /usr/local/share/dvrprocess -name "*.py" -print0 | xargs -r0 python3 -OO -m py_compile
ADD xorg-dummy.conf /etc/
COPY dvrprocess/comskip*.ini /etc/
COPY dvrprocess/media-hare.defaults.ini dvrprocess/media-hare.ini /etc/
COPY profanity-filter-apply.sh /etc/cron.daily/profanity-filter-apply
COPY tvshow-summary.sh /etc/cron.daily/tvshow-summary
#COPY comchap-apply.sh /etc/cron.daily/comchap-apply
COPY comtune-apply.sh /etc/cron.daily/comtune-apply
COPY transcode-apply.sh /etc/cron.hourly/transcode-apply
COPY logrotate.conf /etc/logrotate.d/dvr
COPY sendmail-log.sh /usr/sbin/sendmail
COPY healthcheck.sh /usr/bin/
COPY hwaccel-drivers.sh /usr/bin/hwaccel-drivers
COPY hwaccel-drivers-wrapper.sh /usr/bin/hwaccel-drivers-wrapper
COPY anacron.cron /etc/cron.d/anacron
COPY tesseract-wrapper.sh /usr/bin/tesseract
ADD *.service /etc/systemd/system/
RUN chmod 0644 /etc/logrotate.d/dvr &&\
    find /etc/cron* -type f -print0 | xargs -r0 chmod 0755 &&\
    ln -s /usr/local/share/dvrprocess/dvr_post_process.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/profanity_filter.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/profanity-filter-apply.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/profanity-filter-report.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comchap-apply.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comchap.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comtune.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comcut.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/scene-extract.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/edl-normalize.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/find_need_transcode.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/find_need_comcut.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/transcode-apply.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/smart-comcut.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/tvshow-summary.py /usr/local/bin/ &&\
    chmod +x /usr/local/bin/* /usr/sbin/sendmail /usr/bin/tesseract /usr/bin/hwaccel-drivers* && \
    ln -s /usr/bin/hwaccel-drivers-wrapper /etc/cron.daily/1hwaccel-drivers &&\
    systemctl enable cron &&\
    systemctl enable xorg-dummy &&\
    systemctl enable localtime &&\
    systemctl enable hwaccel-drivers &&\
    echo "DISPLAY=:0" >> /etc/environment &&\
    cat /etc/zsh/newuser.zshrc.recommended > /root/.zshrc

CMD [ "/usr/bin/systemctl", "default" ]

HEALTHCHECK CMD /usr/bin/healthcheck.sh
