FROM ubuntu:24.04 AS comskipbuild

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp
RUN apt-get -q update &&\
    apt-get install -y autoconf libtool git build-essential libargtable2-dev libavformat-dev libsdl1.2-dev libswscale-dev
RUN git clone https://github.com/erikkaashoek/Comskip --branch master --single-branch
RUN cd Comskip &&\
    git reset 55b0bcd018ddb9dacfad79addc48df55c1411073 --hard
RUN cd Comskip &&\
    ./autogen.sh &&\
    ./configure &&\
    make &&\
    make install

FROM ubuntu:24.04 AS ccbuild

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /tmp
RUN apt-get -q update &&\
    apt-get install -y autoconf libtool git build-essential libglew-dev libglfw3-dev cmake gcc libcurl4-gnutls-dev tesseract-ocr libtesseract-dev libleptonica-dev clang libclang-dev
RUN git clone https://github.com/CCExtractor/ccextractor --branch master --single-branch
RUN cd ccextractor &&\
    git reset v0.94 --hard
RUN cd ccextractor/linux &&\
    ./build -without-rust &&\
    ./ccextractor --version &&\
    cp ccextractor /usr/local/bin

FROM ubuntu:24.04

ARG SYSTEMCTL_VER=ac9b3916dd069ba053e4259cf74131028935f5e1
ARG WHISPER_MODEL=medium
ENV DEBIAN_FRONTEND=noninteractive
ENV WHISPER_MODEL=${WHISPER_MODEL}

COPY requirements.txt /usr/local/share/

# mono-* deps line must match Subtitle-Edit version
# mono-devel is required beyond mono-runtime
# hunspell needed for Subtitle-Edit
RUN apt-get -q update && \
    apt-get install -y software-properties-common && \
    apt-get install -qy zsh ffmpeg x264 x265 imagemagick vainfo curl python3 python3-pip python3-dev cron anacron sshfs vim-tiny mkvtoolnix unzip logrotate jq less default-jre rsync \
    mono-runtime libmono-system-windows-forms4.0-cil libmono-system-net-http-webrequest4.0-cil mono-devel libhunspell-dev hunspell-en-us tesseract-ocr-eng xserver-xorg-video-dummy libgtk2.0-0 \
    libargtable2-0 libavformat60 libsdl1.2-compat &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* &&\
    find /etc/cron.*/* -type f -not -name "*logrotate*" -not -name "*anacron*" -delete &&\
    rm -rf /tmp/*

RUN curl -o /tmp/se.zip -L "https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.12/SE4012.zip" &&\
    unzip -d /usr/share/subtitle-edit /tmp/se.zip &&\
    rm /tmp/se.zip &&\
    curl -L -o /usr/bin/systemctl https://github.com/gdraheim/docker-systemctl-replacement/raw/${SYSTEMCTL_VER}/files/docker/systemctl3.py &&\
    chmod +x /usr/bin/systemctl &&\
    useradd -g 100 -u 99 plex

# Settings.xml is generated by running SubtitleEdit.exe and exiting. If re-generating, compare settings. Ensure that the subtitle PNGs are not transparent.
COPY SubtitleEdit-Settings.xml /usr/share/subtitle-edit/Settings.xml
ADD subtitle-edit /usr/local/bin/
COPY --from=comskipbuild /usr/local/bin/comskip /usr/local/bin
COPY --from=ccbuild /usr/local/bin/ccextractor /usr/local/bin
ADD dvrprocess /usr/local/share/dvrprocess/
RUN find /usr/local/share/dvrprocess -name "*.py" -print0 | xargs -r0 python3 -OO -m py_compile
ADD xorg-dummy.conf /etc/
COPY dvrprocess/comskip*.ini dvrprocess/media-hare.defaults.ini dvrprocess/media-hare.ini /etc/
COPY tvshow-summary.sh /etc/cron.daily/tvshow-summary
#COPY comchap-apply.sh /etc/cron.daily/comchap-apply
COPY comtune-apply.sh /etc/cron.daily/comtune-apply
COPY transcode-apply.sh /etc/cron.hourly/transcode-apply
COPY media-errors.sh /etc/cron.daily/media-errors
COPY profanity-filter-apply.sh /etc/cron.daily/profanity-filter-apply
COPY clean-orphaned-files.sh /etc/cron.weekly/clean-orphaned-files
COPY logrotate.conf /etc/logrotate.d/dvr
COPY sendmail-log.sh /usr/sbin/sendmail
COPY healthcheck.sh /usr/bin/
COPY entrypoint.sh /
COPY install-deps.sh /usr/bin/install-deps
COPY hwaccel-drivers.sh /usr/bin/hwaccel-drivers
COPY hwaccel-drivers-wrapper.sh /usr/bin/hwaccel-drivers-wrapper
COPY anacron.cron /etc/cron.d/anacron
COPY auto-upgrade-conf /etc/apt/apt.conf.d/20auto-upgrades
COPY whisper.patch /usr/local/src/
ADD *.service /etc/systemd/system/
RUN chmod 0644 /etc/logrotate.d/dvr &&\
    find /etc/cron* -type f -print0 | xargs -r0 chmod 0755 &&\
    ln -s /usr/local/share/dvrprocess/dvr_post_process.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/profanity_filter.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/profanity-filter-apply.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/profanity-filter-report.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comchap-apply.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comchap.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comtune.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/comcut.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/scene-extract.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/edl_normalize.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/find_need_transcode.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/find_need_comcut.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/find_media_errors.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/transcode-apply.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/smart-comcut.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/tvshow-summary.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/tvshow-suspicious.py /usr/local/bin/ &&\
    ln -s /usr/local/share/dvrprocess/clean_orphaned_files.py /usr/local/bin/ &&\
    chmod +x /usr/local/bin/* /usr/sbin/sendmail /usr/bin/hwaccel-drivers* && \
    ln -s /usr/bin/hwaccel-drivers-wrapper /etc/cron.daily/1hwaccel-drivers &&\
    systemctl enable cron &&\
    systemctl enable xorg-dummy &&\
    systemctl enable localtime &&\
    systemctl enable environment &&\
    systemctl enable install-deps &&\
    systemctl enable hwaccel-drivers &&\
    systemctl disable unattended-upgrades &&\
    echo "DISPLAY=:0" >> /etc/environment &&\
    cat /etc/zsh/newuser.zshrc.recommended > /root/.zshrc

VOLUME ["/usr/local/lib/python3.12", "/var/cache/pip", "/root/.cache/whisper"]

CMD [ "/entrypoint.sh" ]

HEALTHCHECK CMD /usr/bin/healthcheck.sh
